import assert from 'node:assert/strict'
import fs from 'node:fs'

const mineSource = fs.readFileSync(new URL('../pages/mine/index.vue', import.meta.url), 'utf8')
assert.equal(mineSource.includes('官方客服'), true)
assert.equal(mineSource.includes('我的订单'), true)
assert.equal(mineSource.includes('建议反馈'), true)
assert.equal(mineSource.includes('团长切换'), true)
assert.equal(mineSource.includes('open-type="contact"'), true)
assert.equal(mineSource.includes('/static/image/mine/order.png'), true)
assert.equal(mineSource.includes('/static/image/mine/feedback.png'), true)
assert.equal(mineSource.includes('/static/image/mine/service.png'), true)
assert.equal(mineSource.includes('/static/image/mine/switch.png'), true)
assert.equal(mineSource.includes('shortcut-icon'), false)
assert.equal(mineSource.includes('showFeedbackHint'), true)
assert.equal(mineSource.includes('userHeaderStyle'), true)
assert.equal(mineSource.includes('avatarSrc'), true)
assert.equal(mineSource.includes('normalizeMemberInfo'), true)
assert.equal(mineSource.includes('resolveAvatarUrl'), true)
assert.equal(mineSource.includes("token: uni.getStorageSync('token')"), true)
assert.equal(mineSource.includes('flex: 0 0 25%'), true)
assert.equal(mineSource.includes('width: 96rpx'), true)
assert.equal(mineSource.includes('padding-bottom: 26rpx'), true)
assert.equal(mineSource.includes('border-top: 24rpx solid #f6f6f6'), true)
assert.equal(mineSource.includes('logout-btn'), true)
assert.equal(mineSource.includes('await logoutUser()'), true)
assert.equal(mineSource.includes('LOGIN_STORAGE_KEYS.forEach(key => uni.removeStorageSync(key))'), true)
assert.equal(mineSource.includes("'leader_avatar'"), true)
assert.equal(mineSource.includes("uni.setStorageSync('leader_avatar', leaderAvatar)"), true)
assert.equal(mineSource.includes("uni.reLaunch({ url: '/pages/login/index' })"), true)
assert.match(mineSource, /uni\.navigateTo\(\{\s*url,/)
assert.equal(mineSource.includes("uni.reLaunch({ url })"), true)
assert.equal(mineSource.includes("uni.redirectTo({ url: url })"), false)

const distMineSource = fs.readFileSync(new URL('../unpackage/dist/dev/mp-weixin/pages/mine/index.js', import.meta.url), 'utf8')
assert.equal(distMineSource.includes('common_vendor.index.navigateTo({'), true)
const distMineWxml = fs.readFileSync(new URL('../unpackage/dist/dev/mp-weixin/pages/mine/index.wxml', import.meta.url), 'utf8')
assert.equal(distMineWxml.includes('官方客服'), true)
assert.equal(distMineWxml.includes('open-type="contact"'), true)
assert.equal(distMineWxml.includes('menu-icon'), true)
const distAssetsSource = fs.readFileSync(new URL('../unpackage/dist/dev/mp-weixin/common/assets.js', import.meta.url), 'utf8')
assert.equal(distAssetsSource.includes('/static/image/mine/order.png'), true)
assert.equal(distAssetsSource.includes('/static/image/mine/feedback.png'), true)
assert.equal(distAssetsSource.includes('/static/image/mine/service.png'), true)
assert.equal(distAssetsSource.includes('/static/image/mine/switch.png'), true)

const authSource = fs.readFileSync(new URL('../utils/auth.js', import.meta.url), 'utf8')
assert.equal(authSource.includes("if (userInfo.token) uni.setStorageSync('token', userInfo.token)"), true)

console.log('memberLogout tests passed')
