import assert from 'node:assert/strict'
import fs from 'node:fs'

const mineSource = fs.readFileSync(new URL('../pages/mine/index.vue', import.meta.url), 'utf8')
assert.equal(mineSource.includes('官方客服'), true)
assert.equal(mineSource.includes('我的订单'), true)
assert.equal(mineSource.includes('建议反馈'), true)
assert.equal(mineSource.includes('团长切换'), true)
assert.equal(mineSource.includes('open-type="contact"'), true)
assert.equal(mineSource.includes('/static/image/mine/order.png'), true)
assert.equal(mineSource.includes('/static/image/mine/feedback.png'), true)
assert.equal(mineSource.includes('/static/image/mine/service.png'), true)
assert.equal(mineSource.includes('/static/image/mine/switch.png'), true)
assert.equal(mineSource.includes('shortcut-icon'), false)
assert.equal(mineSource.includes('showFeedbackHint'), true)
assert.equal(mineSource.includes('userHeaderStyle'), true)
assert.equal(mineSource.includes('avatarSrc'), true)
assert.equal(mineSource.includes('normalizeMemberInfo'), true)
assert.equal(mineSource.includes('resolveAvatarUrl'), true)
assert.equal(mineSource.includes("token: uni.getStorageSync('token')"), true)
assert.equal(mineSource.includes('flex: 0 0 25%'), true)
assert.equal(mineSource.includes('width: 96rpx'), true)
assert.equal(mineSource.includes('padding-bottom: 26rpx'), true)
assert.equal(mineSource.includes('border-top: 24rpx solid #f6f6f6'), true)
assert.equal(mineSource.includes('logout-btn'), true)
assert.equal(mineSource.includes('await logoutUser()'), true)
assert.equal(mineSource.includes('LOGIN_STORAGE_KEYS.forEach(key => uni.removeStorageSync(key))'), true)
assert.equal(mineSource.includes("'leader_avatar'"), true)
assert.equal(mineSource.includes("uni.setStorageSync('leader_avatar', leaderAvatar)"), true)
assert.equal(mineSource.includes("uni.redirectTo({ url: '/pages/login/index'})"), false)
assert.equal(mineSource.includes('isLoggedIn: false'), true)
assert.equal(mineSource.includes('refreshMemberSession()'), true)
assert.equal(mineSource.includes('requireMemberLogin()'), true)
assert.equal(mineSource.includes("uni.switchTab({ url: '/pages/index/index' })"), true)
assert.match(mineSource, /uni\.navigateTo\(\{\s*url,/)
assert.equal(mineSource.includes("uni.reLaunch({ url })"), true)
assert.equal(mineSource.includes("uni.redirectTo({ url: url })"), false)

const distMineSource = fs.readFileSync(new URL('../unpackage/dist/dev/mp-weixin/pages/mine/index.js', import.meta.url), 'utf8')
assert.equal(distMineSource.includes('common_vendor.index.navigateTo({'), true)
assert.equal(distMineSource.includes('refreshMemberSession()'), true)
assert.equal(distMineSource.includes('redirectTo({ url: "/pages/login/index" })'), false)
const distMineWxml = fs.readFileSync(new URL('../unpackage/dist/dev/mp-weixin/pages/mine/index.wxml', import.meta.url), 'utf8')
assert.equal(distMineWxml.includes('官方客服'), true)
assert.equal(distMineWxml.includes('open-type="contact"'), true)
assert.equal(distMineWxml.includes('menu-icon'), true)

const distLoginSource = fs.readFileSync(new URL('../unpackage/dist/dev/mp-weixin/pages/login/index.js', import.meta.url), 'utf8')
assert.equal(distLoginSource.includes('isAgreementAccepted: false'), true)
assert.equal(distLoginSource.includes('showAgreementModal: false'), true)
assert.equal(distLoginSource.includes('rejectAgreement()'), true)
assert.equal(distLoginSource.includes('if (!this.isAgreementAccepted)'), true)
const distLoginWxml = fs.readFileSync(new URL('../unpackage/dist/dev/mp-weixin/pages/login/index.wxml', import.meta.url), 'utf8')
assert.equal(distLoginWxml.includes('不同意'), true)
assert.equal(distLoginWxml.includes('同意'), true)
assert.equal(distLoginWxml.includes('登录即同意'), false)
assert.equal(distLoginWxml.includes('登陆即同意'), false)

const distArticleSource = fs.readFileSync(new URL('../unpackage/dist/dev/mp-weixin/pages/article/index.js', import.meta.url), 'utf8')
assert.equal(distArticleSource.includes('goBack()'), true)
const distAssetsSource = fs.readFileSync(new URL('../unpackage/dist/dev/mp-weixin/common/assets.js', import.meta.url), 'utf8')
assert.equal(distAssetsSource.includes('/static/image/mine/order.png'), true)
assert.equal(distAssetsSource.includes('/static/image/mine/feedback.png'), true)
assert.equal(distAssetsSource.includes('/static/image/mine/service.png'), true)
assert.equal(distAssetsSource.includes('/static/image/mine/switch.png'), true)

const authSource = fs.readFileSync(new URL('../utils/auth.js', import.meta.url), 'utf8')
assert.equal(authSource.includes("if (userInfo.token) uni.setStorageSync('token', userInfo.token)"), true)

const loginSource = fs.readFileSync(new URL('../pages/login/index.vue', import.meta.url), 'utf8')
assert.equal(loginSource.includes('@click="gotoArticle(1)"'), true)
assert.equal(loginSource.includes('@click="gotoArticle(2)"'), true)
assert.equal(loginSource.includes('isAgreementAccepted: false'), true)
assert.equal(loginSource.includes('showAgreementModal: false'), true)
assert.equal(loginSource.includes('登录即同意'), false)
assert.equal(loginSource.includes('登陆即同意'), false)
assert.equal(loginSource.includes('不同意'), true)
assert.equal(loginSource.includes('acceptAgreement()'), true)
assert.equal(loginSource.includes('rejectAgreement()'), true)
assert.equal(loginSource.includes("pendingAgreementAction = 'submit'"), true)
assert.equal(loginSource.includes("if (!this.isAgreementAccepted)"), true)
assert.equal(loginSource.includes('goBack()'), true)
assert.equal(loginSource.includes('uni.navigateTo({ url: url }).catch'), false)
assert.equal(loginSource.includes('fail: () => { uni.redirectTo({ url }) }'), true)

const appSource = fs.readFileSync(new URL('../App.vue', import.meta.url), 'utf8')
assert.equal(appSource.includes('if(openid && token)'), true)
assert.equal(appSource.includes('this.getWxOpenID()'), false)

const articleSource = fs.readFileSync(new URL('../pages/article/index.vue', import.meta.url), 'utf8')
assert.equal(articleSource.includes('goBack()'), true)
assert.equal(articleSource.includes('article-nav'), true)

const leaderDashboardSource = fs.readFileSync(new URL('../pagesA/dashboard/index.vue', import.meta.url), 'utf8')
assert.equal(leaderDashboardSource.includes('@click="gotoArticle(1)"'), true)
assert.equal(leaderDashboardSource.includes('gotoArticle(articleId)'), true)
assert.equal(leaderDashboardSource.includes('uni.navigateTo({ url }).catch'), false)
assert.equal(leaderDashboardSource.includes('fail: () => { uni.redirectTo({ url }) }'), true)

console.log('memberLogout tests passed')
